version: '3.9'

services:
  django-gdal-app:
    container_name: django-gdal-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app  # Solo durante el desarrollo para trabajar con los archivos locales
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
